### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by lzkamods** [scwmake/SC#1]
i run main.py, it crash! but it can run and shows me menu. crash after

**Comment by Daniil-SV** [comment]
What files did you use?
It would be nice if you uploaded them somewhere so I can check them.

**Comment by lzkamods** [comment]
> What files did you use?
> 
> It would be nice if you uploaded them somewhere so I can check them.

what files?

**Comment by lzkamods** [comment]
> What files did you use?
> 
> It would be nice if you uploaded them somewhere so I can check them.
i see it
![image](https://user-images.githubusercontent.com/104593893/213009966-2fb243db-2dd8-4115-a90e-acd944b6278d.png)![image](https://user-images.githubusercontent.com/104593893/213010064-273dde92-c107-4ffd-be79-8ad0c2501cd6.png)![image](https://user-images.githubusercontent.com/104593893/213010105-e23a2855-0646-4d60-9b25-561baa6cdc8b.png)

**Comment by Daniil-SV** [comment]
just so you know, it's not called a crash.
your command should look like:
py main.py d filename.sc
